base: /
dependencies:
  - host-europe/hosteurope-template
  - host-europe/hosteurope-faq
  - tpwd/ke_search
  - typo3/fluid-styled-content
languages:
  -
    title: German
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: ''
    flag: de
    hreflang: ''
    websiteTitle: ''
  -
    title: English
    enabled: true
    locale: en-GB
    hreflang: ''
    base: /en/
    websiteTitle: ''
    navigationTitle: ''
    fallbackType: strict
    fallbacks: ''
    flag: gb
    languageId: 1
rootPageId: 1
websiteTitle: ''
routeEnhancers:
  FaqMain:
    type: Extbase
    limitToPages: [69, 60]
    extension: HosteuropeFaq
    plugin: Main
    routes:
      - routePath: '/{slug_0}'
        _controller: 'Category::router'
        _arguments:
          slug_0: 'slug/0'
      - routePath: '/{slug_0}/{slug_1}'
        _controller: 'Category::router'
        _arguments:
          slug_0: 'slug/0'
          slug_1: 'slug/1'
      - routePath: '/{slug_0}/{slug_1}/{slug_2}'
        _controller: 'Category::router'
        _arguments:
          slug_0: 'slug/0'
          slug_1: 'slug/1'
          slug_2: 'slug/2'
    defaultController: 'Category::router'
