<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hosteurope_faq"
 *
 * Auto generated by Extension Builder 2016-05-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Hosteurope FAQ',
	'description' => 'Host Europe GmbH FAQ',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
      'typo3' => '13.4.0-13.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);