MellonPostDirectory "/var/cache/apache2/mod_auth_mellon/"


MellonCacheSize 100
MellonLockFile "/var/lock/mod_auth_mellon.lock"


<Location /typo3 >
    # general config
    MellonEnable "auth"
    AuthType "Mellon"
    MellonVariable "cookie"
    MellonSamlResponseDump On

    ## files generated
    MellonSPMetadataFile /etc/apache2/mellon/he_faq_edit_staging_0242ac120002.xml
    MellonSPPrivateKeyFile /etc/apache2/mellon/he_faq_edit_staging_0242ac120002.key
    MellonSPCertFile /etc/apache2/mellon/he_faq_edit_staging_0242ac120002.cert
    MellonIdPMetadataFile /etc/apache2/mellon/idp.xml

    # endpoint
    MellonEndpointPath /typo3/secret/endpoint
    MellonSecureCookie On
    MellonCookieSameSite none

    # session cookie duration; 43200(secs) = 12 hours
    MellonSessionLength 43200
    MellonUser "NAME_ID"
    MellonDefaultLoginPath /typo3
    MellonSamlResponseDump On

    #Require valid-user
    #Order allow,deny
    #Satisfy any
</Location>

<Location /secret/endpoint/>
   AuthType "Mellon"
   MellonEnable "off"
   Order Deny,Allow
   Allow from all
   Satisfy Any
</Location>